services:
  netssl:
    build:
      context: . # Use root directory for unified Dockerfile
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in container (nginx)
    env_file:
      - .env
    volumes:
      - backend_accounts:/app/backend/accounts  # Persistent storage for certificates and accounts
      - backend_db:/app/backend/db              # Persistent storage for database
    restart: unless-stopped

volumes:
  backend_accounts:
    driver: local
  backend_db:
    driver: local
