services:
  netssl:
    build:
      context: . # Use root directory for unified Dockerfile
    ports:
      - "3000:80" # Map port 3000 on host to port 80 in container (nginx)
    env_file:
      - .env
    volumes:
      - ./backend/accounts:/app/accounts  # Persistent storage for certificates and accounts
      - ./backend/db:/app/db              # Persistent storage for database
    restart: unless-stopped
