# Docker Compose for Development Testing
# This uses local builds instead of pulling from registry

name: react-express-tailwind-app

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - PORT=${PORT:-3001}
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - VITE_API_URL=/api
      - VITE_BRANDING_NAME=${VITE_BRANDING_NAME:-Automate Builders}
      - VITE_BRANDING_URL=${VITE_BRANDING_URL:-https://automate.builders}
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: react-backend
    expose:
      - "${PORT:-3001}"
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - app-network
    environment:
      - PORT=${PORT:-3001}
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - backend_data:/app/backend/db
      - backend_accounts:/app/backend/accounts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local
  backend_accounts:
    driver: local

networks:
  app-network:
    driver: bridge