# Docker Compose for VOS SSH Dashboard - Single Container Deployment
# This pulls the unified image from GitHub Container Registry

name: netssl

services:
  app:
    image: ghcr.io/sieteunoseis/netssl:${TAG:-latest}
    container_name: netssl-dashboard
    ports:
      - "3000:80"  # nginx serves frontend and proxies API
    env_file:
      - .env
    volumes:
      - app_db:/app/backend/db  # Persist database
      - app_accounts:/app/backend/accounts  # Persist certificates and accounts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/data"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  app_db:
    driver: local
  app_accounts:
    driver: local