# Docker Compose for VOS SSH Dashboard - Single Container Deployment
# This pulls the unified image from GitHub Container Registry

name: netssl

services:
  app:
    image: ghcr.io/sieteunoseis/netssl:${TAG:-latest}
    container_name: netssl-dashboard
    ports:
      - "3000:80"  # nginx serves frontend and proxies API
    environment:
      - PORT=${PORT:-5000}  # Internal backend port
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_BRANDING_NAME=${VITE_BRANDING_NAME:-VOS Certificate Management}
      - VITE_BRANDING_URL=${VITE_BRANDING_URL:-https://automate.builders}
      - VITE_TABLE_COLUMNS=${VITE_TABLE_COLUMNS:-name,hostname,username,password,version}
      - LETSENCRYPT_STAGING=${LETSENCRYPT_STAGING:-false}
    volumes:
      - app_db:/app/db  # Persist database
      - app_accounts:/app/accounts  # Persist certificates and accounts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/data"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  app_db:
    driver: local
  app_accounts:
    driver: local